#line 2 "src/ras/tokenizer.yy.c"

#line 4 "src/ras/tokenizer.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[257] =
    {   0,
        0,    0,  108,  107,   90,   91,  107,  107,  102,  102,
        1,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,   90,   91,    0,    0,
        0,   92,   92,   97,    0,    0,  102,  100,  106,  106,
      106,    1,  101,  106,  106,  106,  106,  106,  106,   31,
      106,  106,  106,  106,  106,  106,   30,  106,   41,   12,
      106,  106,    2,    3,    4,    5,    6,    7,    8,    9,
      106,  106,  106,   10,   11,  106,  106,   32,  106,  106,

      106,  106,  106,  106,  106,  106,  106,   34,  106,  106,
      106,  106,  106,  106,   33,  106,   50,   26,  106,  106,
       16,   17,   18,   19,   20,   21,   22,   23,  106,  106,
      106,   24,   25,  106,  106,   35,  106,  106,  106,    0,
        0,   92,   97,   97,  105,  104,  103,   36,   42,  106,
      106,   39,  106,  106,  106,   40,  106,  106,  106,   54,
       56,   13,   72,  106,  106,  106,  106,   66,  106,   37,
      106,   43,  106,   45,   51,  106,  106,   48,  106,  106,
      106,   49,  106,  106,  106,   55,   57,   27,   73,  106,
      106,  106,  106,   67,  106,   46,  106,   52,  106,   96,

       95,   94,   93,   99,   98,  106,   70,   82,   76,   86,
       15,   64,   38,   74,  106,  106,  106,  106,   78,   14,
      106,   71,   83,   77,   87,   29,   65,   47,   75,  106,
      106,  106,  106,   79,   28,   84,   62,   58,   68,  106,
      106,   88,   85,   63,   59,   69,  106,  106,   89,   60,
       80,   44,   61,   81,   53,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    7,    1,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   16,   17,   18,    1,
        1,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   35,   41,   35,   42,
        1,    1,    1,    1,    1,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   35,   59,   60,   61,   62,   63,   35,   64,
       35,   65,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[66] =
    {   0,
        1,    2,    3,    4,    1,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    2,    1,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5
    } ;

static yyconst flex_uint16_t yy_base[263] =
    {   0,
        0,    0,  162,  951,  135,  130,   62,    0,   77,  140,
        0,   78,   79,   65,   81,   95,   97,  100,  101,  102,
      105,  103,  141,  143,  181,  182,  144,  130,  111,  113,
      168,  164,  184,  170,  186,  195,  122,  198,  206,  200,
      207,  268,  228,  237,  208,  225,  127,  124,    0,    0,
      289,  322,  162,  225,  119,  217,  385,  951,  226,  304,
      395,    0,  951,  244,  245,  290,  292,  234,  322,  256,
      325,  291,  338,  341,  342,  344,  345,  346,  347,  348,
      351,  355,  371,  372,  373,  374,  410,  411,  418,  419,
      420,  427,  428,  429,  430,  431,  451,  432,  453,  452,

      457,  458,  459,  460,  461,  465,  477,  478,  479,  481,
      483,  482,  484,  489,  485,  490,  495,  501,  506,  508,
      509,  518,  525,  528,  530,  536,  538,  539,  541,  542,
      546,  549,  550,  552,  555,  558,  563,  559,  560,  119,
      105,  573,  310,  612,  951,  588,   89,  576,  577,  593,
      613,  596,  627,  635,  644,  636,  645,  647,  637,  646,
      665,  669,  670,  671,  672,  675,  677,  676,  681,  682,
      688,  683,  699,  689,  701,  702,  706,  707,  708,  709,
      710,  711,  718,  719,  713,  727,  729,  731,  732,  735,
      736,  737,  738,  740,  741,  759,  760,  761,  762,  951,

      951,  764,    0,  951,  951,  773,  778,  780,  784,  786,
      787,  789,  790,  791,  792,  796,  803,  794,  808,  810,
      812,  819,  820,  821,  822,  826,  829,  831,  832,  833,
      838,  840,  842,  843,  845,  849,  850,  851,  852,  856,
      859,  854,  861,  862,  868,  870,  873,  878,  879,  881,
      882,  889,  891,  898,  900,  951,  926,  931,  935,  940,
       96,  945
    } ;

static yyconst flex_int16_t yy_def[263] =
    {   0,
      256,    1,  256,  256,  256,  256,  257,  258,  259,  259,
      260,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  256,  256,  261,  262,
      256,  257,   52,  257,  256,  256,  259,  256,  259,  259,
       42,  260,  256,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  261,
      256,  256,  257,   52,  256,  259,   61,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  256,

      256,  257,  144,  256,  256,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,    0,  256,  256,  256,  256,
      256,  256
    } ;

static yyconst flex_uint16_t yy_nxt[1017] =
    {   0,
        4,    5,    6,    4,    7,    8,    4,    9,   10,   10,
       10,   10,   10,   10,   10,   10,    4,   11,   12,   13,
       14,   15,   16,   16,   16,   17,   18,   19,   16,   20,
       21,   22,   23,   24,   16,   25,   26,   27,   16,   16,
       28,   29,   30,   31,   32,   33,   16,   16,   16,   34,
       35,   36,   16,   37,   38,   39,   40,   41,   42,   43,
       44,   16,   16,   45,   46,   49,   56,   50,   51,   52,
       53,   53,   53,   53,   53,   53,   53,   53,   56,   56,
       56,   63,   56,   67,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   58,   63,   63,   56,   63,   56,   64,

      140,   56,   56,   56,   56,  205,   56,   68,   66,   65,
      201,   63,   56,   63,   56,   69,   63,   63,   63,   63,
       60,   63,  200,   56,  145,   75,   48,   63,   47,   63,
       70,   56,   48,  101,   72,   76,   47,   73,   63,   71,
       61,   56,   56,   74,   56,   56,   63,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   58,   63,  102,   63,
       63,  256,  100,   80,   77,   56,  256,  256,  103,   56,
       98,   56,   78,  256,  256,   81,   79,  256,  110,   99,
       63,   82,   56,   56,   63,   56,   63,   56,   83,   84,
       85,   86,   87,   88,   89,   90,   56,   63,   63,   56,

       63,   56,   63,   91,   93,   54,  105,   56,   56,   56,
      256,   63,  107,   92,   63,   94,   63,   95,   56,   96,
       97,  104,   63,   63,   63,   54,   56,   56,  256,   56,
      256,  256,  256,   63,  106,   56,  256,  256,   56,  256,
      108,   63,   63,  256,   63,   56,   56,  115,  256,  256,
       63,  118,  113,   63,  111,  116,  109,   56,  117,  112,
       63,   63,  114,  119,  138,  148,  149,  256,  120,   56,
      256,  139,   63,  152,  131,  121,  122,  123,  124,  125,
      126,  127,  128,  256,   63,  132,  133,  136,  134,  135,
      256,   56,   56,   56,  256,  137,  142,  142,  142,  142,

      142,  142,  142,  142,  142,   56,   63,   63,   63,  155,
      256,  146,  146,  256,  129,  256,  256,  202,  202,  256,
       63,  151,  150,   56,  130,  256,   56,  256,  256,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   63,   56,
      256,   63,   56,   56,  256,   56,   56,   56,   56,   56,
      256,  153,   56,  256,   63,  154,   56,   63,   63,  156,
       63,   63,   63,   63,   63,  143,  160,   63,  162,  157,
      159,   63,   56,   56,   56,   56,  256,  158,  256,  256,
      256,  161,  256,  256,  163,  144,   56,   63,   63,   63,
       63,  164,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   58,  147,  147,  147,  147,  147,  147,  147,  147,
      147,   56,   56,  147,  147,  147,  147,  147,  147,   56,
       56,   56,  256,  256,  256,  256,   63,   63,   56,   56,
       56,   56,   56,   56,   63,   63,   63,  147,  147,  147,
      147,  147,  147,   63,   63,   63,   63,   63,   63,  256,
      256,   59,   56,   56,   56,  256,  165,  166,   56,   56,
       56,   56,   56,  169,  167,  168,   56,   63,   63,   63,
      170,  171,  256,   63,   63,   63,   63,   63,   56,   56,
       56,   63,   56,   56,   56,   56,   56,  172,  256,  256,
       56,   56,  173,   63,   63,   63,   56,   63,   63,   63,

       63,   63,   56,  174,  175,   63,   63,   56,  256,   56,
       56,   63,  256,  256,  177,  256,  176,   63,  256,   56,
      256,  256,   63,  181,   63,   63,   56,  178,  182,   56,
      179,   56,  186,  180,   63,  185,  188,   56,  183,   56,
       56,   63,   56,   56,   63,  184,   63,   56,  256,  187,
       56,   56,   63,   56,   63,   63,   56,   63,   63,   56,
       56,   56,   63,  189,   56,   63,   63,  190,   63,  256,
      256,   63,  256,  256,   63,   63,   63,   56,   56,   63,
      142,  142,  142,  142,  142,  142,  142,  142,  142,   56,
      256,  256,   63,   63,   56,  146,  146,   56,  196,  256,

      191,  192,  193,  256,  204,  197,  194,  256,  195,   63,
      256,  256,   63,  206,   56,  256,  256,  198,  199,  203,
      203,  203,  203,  203,  203,  203,  203,  203,   56,   63,
      203,  203,  203,  203,  203,  203,   56,   56,   56,  256,
      256,  256,  207,   63,  256,   56,   56,   56,   56,  256,
      256,   63,   63,   63,  203,  203,  203,  203,  203,  203,
       63,   63,   63,   63,  208,  210,   56,  211,  209,  212,
       56,   56,   56,   56,  213,   54,   56,   56,   56,  256,
      256,   63,   56,   56,   56,   63,   63,   63,   63,   56,
       56,   63,   63,   63,  215,  217,  214,   63,   63,   63,

       56,  256,   56,   56,   63,   63,  256,   56,   56,   56,
       56,   56,   56,  216,   56,   63,  218,   63,   63,   56,
       56,  219,   63,   63,   63,   63,   63,   63,   56,   63,
       56,  220,   56,   56,   63,   63,   56,   56,   56,   56,
      256,   56,   56,   63,  256,   63,  221,   63,   63,  256,
      256,   63,   63,   63,   63,  225,   63,   63,  256,  222,
       56,   56,   56,   56,  226,  227,  224,  256,  223,  256,
      256,  202,  202,  228,   56,   63,   63,   63,   63,   56,
      232,   56,  230,  256,  229,   56,  256,   56,   56,   63,
       56,   56,   56,   56,   63,   56,   63,   56,  231,  233,

       63,  236,   63,   63,   56,   63,   63,   63,   63,   56,
       63,   56,   63,   56,  256,  237,  242,  234,  235,   63,
       56,   56,   56,   56,   63,  238,   63,   56,   63,  239,
       56,  240,   56,   56,   56,   63,   63,   63,   63,   56,
      241,   56,   63,   56,   56,   63,   56,   63,   63,   63,
       56,   56,   56,   56,   63,   56,   63,   56,   63,   63,
       56,   63,   56,   56,  243,   63,   63,   63,   63,   56,
       63,   56,   63,  256,   56,   63,  244,   63,   63,   56,
       56,  252,   56,   56,   63,  245,   63,  251,  249,   63,
       56,  250,   56,  246,   63,   63,  247,   63,   63,   56,

      248,   56,  256,  256,  256,   63,  256,   63,  256,  256,
      256,  256,  256,  256,   63,  256,   63,  256,  256,  256,
      256,  256,  256,  256,  255,  256,  253,  256,  254,   54,
       54,   55,   55,  256,   55,   55,   59,  256,  256,   59,
       62,   62,  256,   62,   62,  141,  141,  256,  141,  141,
        3,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256
    } ;

static yyconst flex_int16_t yy_chk[1017] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    7,   14,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    9,   12,
       13,   14,   15,   14,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   12,   13,   16,   15,   17,   12,

      261,   18,   19,   20,   22,  147,   21,   15,   13,   12,
      141,   16,   29,   17,   30,   17,   18,   19,   20,   22,
        9,   21,  140,   37,   55,   22,   48,   29,   47,   30,
       18,   28,    6,   29,   20,   22,    5,   21,   37,   19,
        9,   10,   23,   21,   24,   27,   28,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   23,   30,   24,
       27,    3,   28,   24,   23,   32,    0,    0,   30,   31,
       27,   34,   23,    0,    0,   24,   23,    0,   37,   27,
       32,   24,   25,   26,   31,   33,   34,   35,   25,   25,
       25,   25,   25,   25,   25,   25,   36,   25,   26,   38,

       33,   40,   35,   25,   26,   53,   32,   39,   41,   45,
        0,   36,   34,   25,   38,   26,   40,   26,   56,   26,
       26,   31,   39,   41,   45,   53,   46,   59,   54,   43,
       54,   54,    0,   56,   33,   68,    0,    0,   44,    0,
       35,   46,   59,    0,   43,   64,   65,   40,    0,    0,
       68,   41,   39,   44,   38,   40,   36,   70,   40,   38,
       64,   65,   39,   41,   45,   64,   65,    0,   41,   42,
        0,   46,   70,   68,   43,   42,   42,   42,   42,   42,
       42,   42,   42,    0,   42,   43,   43,   44,   43,   43,
        0,   66,   72,   67,    0,   44,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   60,   66,   72,   67,   72,
        0,   60,   60,  143,   42,  143,  143,  143,  143,    0,
       60,   67,   66,   69,   42,   52,   71,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   69,   73,
        0,   71,   74,   75,    0,   76,   77,   78,   79,   80,
        0,   69,   81,    0,   73,   71,   82,   74,   75,   73,
       76,   77,   78,   79,   80,   52,   75,   81,   78,   73,
       74,   82,   83,   84,   85,   86,    0,   73,    0,    0,
        0,   76,    0,    0,   81,   52,   57,   83,   84,   85,
       86,   82,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   87,   88,   61,   61,   61,   61,   61,   61,   89,
       90,   91,    0,    0,    0,    0,   87,   88,   92,   93,
       94,   95,   96,   98,   89,   90,   91,   61,   61,   61,
       61,   61,   61,   92,   93,   94,   95,   96,   98,    0,
        0,   61,   97,  100,   99,    0,   91,   91,  101,  102,
      103,  104,  105,   96,   92,   93,  106,   97,  100,   99,
       97,   99,    0,  101,  102,  103,  104,  105,  107,  108,
      109,  106,  110,  112,  111,  113,  115,  100,    0,    0,
      114,  116,  101,  107,  108,  109,  117,  110,  112,  111,

      113,  115,  118,  102,  103,  114,  116,  119,    0,  120,
      121,  117,    0,    0,  105,    0,  104,  118,    0,  122,
        0,    0,  119,  110,  120,  121,  123,  106,  111,  124,
      107,  125,  113,  109,  122,  112,  116,  126,  111,  127,
      128,  123,  129,  130,  124,  111,  125,  131,    0,  114,
      132,  133,  126,  134,  127,  128,  135,  129,  130,  136,
      138,  139,  131,  119,  137,  132,  133,  120,  134,    0,
        0,  135,    0,    0,  136,  138,  139,  148,  149,  137,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  146,
        0,    0,  148,  149,  150,  146,  146,  152,  135,    0,

      129,  129,  130,    0,  146,  137,  131,    0,  134,  150,
        0,    0,  152,  150,  151,    0,    0,  138,  139,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  153,  151,
      144,  144,  144,  144,  144,  144,  154,  156,  159,    0,
        0,    0,  151,  153,    0,  155,  157,  160,  158,    0,
        0,  154,  156,  159,  144,  144,  144,  144,  144,  144,
      155,  157,  160,  158,  153,  155,  161,  157,  154,  158,
      162,  163,  164,  165,  159,  144,  166,  168,  167,    0,
        0,  161,  169,  170,  172,  162,  163,  164,  165,  171,
      174,  166,  168,  167,  165,  167,  164,  169,  170,  172,

      173,    0,  175,  176,  171,  174,    0,  177,  178,  179,
      180,  181,  182,  166,  185,  173,  169,  175,  176,  183,
      184,  171,  177,  178,  179,  180,  181,  182,  186,  185,
      187,  173,  188,  189,  183,  184,  190,  191,  192,  193,
        0,  194,  195,  186,    0,  187,  176,  188,  189,    0,
        0,  190,  191,  192,  193,  181,  194,  195,    0,  177,
      196,  197,  198,  199,  183,  184,  180,  202,  179,  202,
      202,  202,  202,  185,  206,  196,  197,  198,  199,  207,
      193,  208,  191,    0,  190,  209,    0,  210,  211,  206,
      212,  213,  214,  215,  207,  218,  208,  216,  192,  195,

      209,  206,  210,  211,  217,  212,  213,  214,  215,  219,
      218,  220,  216,  221,    0,  209,  218,  197,  199,  217,
      222,  223,  224,  225,  219,  209,  220,  226,  221,  215,
      227,  216,  228,  229,  230,  222,  223,  224,  225,  231,
      217,  232,  226,  233,  234,  227,  235,  228,  229,  230,
      236,  237,  238,  239,  231,  242,  232,  240,  233,  234,
      241,  235,  243,  244,  221,  236,  237,  238,  239,  245,
      242,  246,  240,    0,  247,  241,  224,  243,  244,  248,
      249,  241,  250,  251,  245,  224,  246,  240,  233,  247,
      252,  237,  253,  230,  248,  249,  231,  250,  251,  254,

      232,  255,    0,    0,    0,  252,    0,  253,    0,    0,
        0,    0,    0,    0,  254,    0,  255,    0,    0,    0,
        0,    0,    0,    0,  248,    0,  244,    0,  247,  257,
      257,  258,  258,    0,  258,  258,  259,    0,    0,  259,
      260,  260,    0,  260,  260,  262,  262,    0,  262,  262,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/ras/tokenizer.l"
#line 4 "src/ras/tokenizer.l"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "parser.h"
#include "parser.tab.h"

#define YY_DECL int yylex()

extern int fileno(FILE *stream);

char* strdup(const char* str){
    char* out = (char*) malloc(strlen(str));
    int i = 0;
    while (str[i] != ' ' && str[i] != '\t' && str[i] != ':' && str[i]){
        out[i] = str[i];
        i++;
    }
    out[i] = 0;
    return out;
}

#line 803 "src/ras/tokenizer.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 28 "src/ras/tokenizer.l"


#line 1024 "src/ras/tokenizer.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 257 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 951 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "src/ras/tokenizer.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 32 "src/ras/tokenizer.l"
yylval.regval = REG0; return REG;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "src/ras/tokenizer.l"
yylval.regval = REG1; return REG;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "src/ras/tokenizer.l"
yylval.regval = REG2; return REG;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "src/ras/tokenizer.l"
yylval.regval = REG3; return REG;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "src/ras/tokenizer.l"
yylval.regval = REG4; return REG;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "src/ras/tokenizer.l"
yylval.regval = REG5; return REG;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "src/ras/tokenizer.l"
yylval.regval = REG6; return REG;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "src/ras/tokenizer.l"
yylval.regval = REG7; return REG;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "src/ras/tokenizer.l"
yylval.regval = SP; return REG;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "src/ras/tokenizer.l"
yylval.regval = SR; return REG;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 42 "src/ras/tokenizer.l"
yylval.regval = PC; return REG;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "src/ras/tokenizer.l"
yylval.regval = ONE; return REG;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "src/ras/tokenizer.l"
yylval.regval = ZERO; return REG;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "src/ras/tokenizer.l"
yylval.regval = MONE; return REG;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "src/ras/tokenizer.l"
yylval.regval = REG0; return REG;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "src/ras/tokenizer.l"
yylval.regval = REG1; return REG;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "src/ras/tokenizer.l"
yylval.regval = REG2; return REG;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "src/ras/tokenizer.l"
yylval.regval = REG3; return REG;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "src/ras/tokenizer.l"
yylval.regval = REG4; return REG;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "src/ras/tokenizer.l"
yylval.regval = REG5; return REG;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "src/ras/tokenizer.l"
yylval.regval = REG6; return REG;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "src/ras/tokenizer.l"
yylval.regval = REG7; return REG;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "src/ras/tokenizer.l"
yylval.regval = SP; return REG;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "src/ras/tokenizer.l"
yylval.regval = SR; return REG;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "src/ras/tokenizer.l"
yylval.regval = PC; return REG;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "src/ras/tokenizer.l"
yylval.regval = ONE; return REG;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "src/ras/tokenizer.l"
yylval.regval = ZERO; return REG;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "src/ras/tokenizer.l"
yylval.regval = MONE; return REG;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "src/ras/tokenizer.l"
yylval.ival = 0; return INT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "src/ras/tokenizer.l"
yylval.ival = 1; return INT;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "src/ras/tokenizer.l"
yylval.ival = 2; return INT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "src/ras/tokenizer.l"
yylval.ival = 0; return INT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "src/ras/tokenizer.l"
yylval.ival = 1; return INT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "src/ras/tokenizer.l"
yylval.ival = 2; return INT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "src/ras/tokenizer.l"
yylval.ternval = ADD; return TERNOP;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "src/ras/tokenizer.l"
yylval.ternval = SUB; return TERNOP;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "src/ras/tokenizer.l"
yylval.ternval = MULT; return TERNOP;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "src/ras/tokenizer.l"
yylval.ternval = DIV; return TERNOP;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "src/ras/tokenizer.l"
yylval.ternval = MOD; return TERNOP;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "src/ras/tokenizer.l"
yylval.ternval = OR; return TERNOP;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "src/ras/tokenizer.l"
yylval.ternval = AND; return TERNOP;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "src/ras/tokenizer.l"
yylval.ternval = XOR; return TERNOP;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "src/ras/tokenizer.l"
yylval.ternval = ROTATE; return TERNOP;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "src/ras/tokenizer.l"
yylval.ternval = ADD; return TERNOP;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "src/ras/tokenizer.l"
yylval.ternval = SUB; return TERNOP;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "src/ras/tokenizer.l"
yylval.ternval = MULT; return TERNOP;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "src/ras/tokenizer.l"
yylval.ternval = DIV; return TERNOP;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "src/ras/tokenizer.l"
yylval.ternval = MOD; return TERNOP;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 86 "src/ras/tokenizer.l"
yylval.ternval = OR; return TERNOP;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "src/ras/tokenizer.l"
yylval.ternval = AND; return TERNOP;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 "src/ras/tokenizer.l"
yylval.ternval = XOR; return TERNOP;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "src/ras/tokenizer.l"
yylval.ternval = ROTATE; return TERNOP;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "src/ras/tokenizer.l"
return NEG_TOKEN;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "src/ras/tokenizer.l"
return NEG_TOKEN;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 93 "src/ras/tokenizer.l"
return NOT_TOKEN;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 94 "src/ras/tokenizer.l"
return NOT_TOKEN;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 95 "src/ras/tokenizer.l"
return JUMPZ_TOKEN;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 96 "src/ras/tokenizer.l"
return JUMPZ_TOKEN;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 97 "src/ras/tokenizer.l"
return JUMPNZ_TOKEN;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 98 "src/ras/tokenizer.l"
return JUMPNZ_TOKEN;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 99 "src/ras/tokenizer.l"
return JUMPN_TOKEN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 100 "src/ras/tokenizer.l"
return JUMPN_TOKEN;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 101 "src/ras/tokenizer.l"
return MOVE_TOKEN;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 102 "src/ras/tokenizer.l"
return MOVE_TOKEN;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 103 "src/ras/tokenizer.l"
return SET_TOKEN;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 104 "src/ras/tokenizer.l"
return SET_TOKEN;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 105 "src/ras/tokenizer.l"
return RESET_TOKEN;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 106 "src/ras/tokenizer.l"
return RESET_TOKEN;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 107 "src/ras/tokenizer.l"
return CALL_TOKEN;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 108 "src/ras/tokenizer.l"
return CALL_TOKEN;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 109 "src/ras/tokenizer.l"
return POP_TOKEN;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 110 "src/ras/tokenizer.l"
return POP_TOKEN;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 111 "src/ras/tokenizer.l"
return PUSH_TOKEN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 112 "src/ras/tokenizer.l"
return PUSH_TOKEN;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 113 "src/ras/tokenizer.l"
return JUMP_TOKEN;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 114 "src/ras/tokenizer.l"
return JUMP_TOKEN;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 "src/ras/tokenizer.l"
return TRAP_TOKEN;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 116 "src/ras/tokenizer.l"
return TRAP_TOKEN;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 117 "src/ras/tokenizer.l"
return RETURN_TOKEN;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 118 "src/ras/tokenizer.l"
return RETURN_TOKEN;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 119 "src/ras/tokenizer.l"
return HALT_TOKEN;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 120 "src/ras/tokenizer.l"
return HALT_TOKEN;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 121 "src/ras/tokenizer.l"
return BLOCK_TOKEN;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 122 "src/ras/tokenizer.l"
return BLOCK_TOKEN;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 123 "src/ras/tokenizer.l"
return LOAD_TOKEN;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 124 "src/ras/tokenizer.l"
return LOAD_TOKEN;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 125 "src/ras/tokenizer.l"
return STORE_TOKEN;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 126 "src/ras/tokenizer.l"
return STORE_TOKEN;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 128 "src/ras/tokenizer.l"

	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 130 "src/ras/tokenizer.l"
return ENDL;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 132 "src/ras/tokenizer.l"
sscanf(yytext, "#%d", &yylval.ival); return IMMEDIATEINT;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 133 "src/ras/tokenizer.l"
sscanf(yytext, "#%x", &yylval.ival); return IMMEDIATEINT;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 134 "src/ras/tokenizer.l"
sscanf(yytext, "#0b%i", &yylval.ival); return IMMEDIATEINT;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 135 "src/ras/tokenizer.l"
yylval.ival = (int32_t) yytext[2]; return IMMEDIATEINT;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 136 "src/ras/tokenizer.l"
yylval.sval = strdup(yytext+1); return IMMEDIATESTRING;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 137 "src/ras/tokenizer.l"
yylval.sval = strdup(yytext+1); return IMMEDIATELABLE;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 139 "src/ras/tokenizer.l"
sscanf(yytext, "%x:", &yylval.ival); return INTLABLEDEF_TOKEN;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 140 "src/ras/tokenizer.l"
sscanf(yytext, "0b%i:", &yylval.ival); return INTLABLEDEF_TOKEN;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 141 "src/ras/tokenizer.l"
sscanf(yytext, "%d:", &yylval.ival); return INTLABLEDEF_TOKEN;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 142 "src/ras/tokenizer.l"
yylval.sval = strdup(yytext); return LABLEDEF_TOKEN;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 144 "src/ras/tokenizer.l"
sscanf(yytext, "%d", &yylval.ival); return INT;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 145 "src/ras/tokenizer.l"
sscanf(yytext, "%x", &yylval.ival); return INT;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 146 "src/ras/tokenizer.l"
sscanf(yytext, "0b%i", &yylval.ival); return INT;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 147 "src/ras/tokenizer.l"
yylval.ival = (int32_t) yytext[1]; return INT;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 149 "src/ras/tokenizer.l"
yylval.sval = strdup(yytext); return LABLE;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 151 "src/ras/tokenizer.l"
ECHO;
	YY_BREAK
#line 1617 "src/ras/tokenizer.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 257 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 257 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 256);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 151 "src/ras/tokenizer.l"



